GET http://localhost:8080/api/users/john

###

GET http://localhost:8080/

###

POST http://localhost:8080/signup
Content-Type: application/json

{
  "mail": "hogefuga@mail.com",
  "password": "hogefuga"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "mail": "hoge@mail.com",
  "password": "hogefuga"
}
